-- ============================================================================
-- ICP Server Oracle Credentials Database Schema (Oracle Database 19c)
-- This database is separate from the main ICP database and is only accessed
-- by the default authentication backend for user credential management.
-- Run via SQL*Plus / SQLcl. PL/SQL blocks are terminated with a '/' line.
-- ============================================================================

-- Session-format safety net: make implicit string->timestamp conversions from
-- the application behave deterministically for every session in this schema.
BEGIN
  EXECUTE IMMEDIATE q'[CREATE OR REPLACE TRIGGER icp_set_nls_on_logon AFTER LOGON ON SCHEMA
  BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_TIMESTAMP_FORMAT = ''YYYY-MM-DD HH24:MI:SS.FF6''';
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_DATE_FORMAT = ''YYYY-MM-DD HH24:MI:SS''';
  END;]';
END;
/

-- ============================================================================
-- USER CREDENTIALS TABLE
-- ============================================================================

-- MySQL CREATE TABLE IF NOT EXISTS: emulated by ignoring ORA-00955 (name is
-- already used by an existing object) so the script stays re-runnable.
BEGIN
    EXECUTE IMMEDIATE q'[CREATE TABLE user_credentials (
        user_id CHAR(36) NOT NULL PRIMARY KEY,
        username VARCHAR2(255 CHAR) NOT NULL UNIQUE,
        display_name VARCHAR2(200 CHAR) NOT NULL,
        password_hash VARCHAR2(255 CHAR) NOT NULL,
        password_salt VARCHAR2(255 CHAR),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- idx_user_credentials_username omitted: the UNIQUE constraint on username
-- already creates an index on the same column list (a duplicate raises ORA-01408).

-- ============================================================================
-- USER ATTRIBUTES (EAV key-value store per user)
-- Inspired by UM_USER_ATTRIBUTE from WSO2 MI user store schema.
-- ============================================================================

BEGIN
    EXECUTE IMMEDIATE q'[CREATE TABLE user_attributes (
        id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
        user_id CHAR(36) NOT NULL,
        attr_name VARCHAR2(255 CHAR) NOT NULL,
        attr_value VARCHAR2(1024 CHAR),
        profile_id VARCHAR2(255 CHAR) DEFAULT 'default' NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        PRIMARY KEY (id),
        CONSTRAINT fk_user_attributes_user FOREIGN KEY (user_id)
            REFERENCES user_credentials (user_id) ON DELETE CASCADE,
        CONSTRAINT uk_user_attr_profile UNIQUE (user_id, attr_name, profile_id)
    )]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_ua_user_id ON user_attributes (user_id)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_ua_attr_name ON user_attributes (attr_name)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_ua_user_attr ON user_attributes (user_id, attr_name)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- NOTE: MySQL maintains updated_at via ON UPDATE CURRENT_TIMESTAMP on both
-- tables. The PostgreSQL and MSSQL credentials scripts do not maintain it
-- (no triggers), so no updated_at triggers are created here either; the
-- application must set updated_at explicitly on update.

-- ============================================================================
-- SAMPLE DATA FOR TESTING, MUST BE CHANGED FOR PRODUCTION
-- ============================================================================

-- Insert credentials for admin user (only if not exists)
-- (MySQL INSERT IGNORE: emulated with a NOT EXISTS guard)
INSERT INTO user_credentials (
    user_id,
    username,
    display_name,
    password_hash
)
SELECT
    '550e8400-e29b-41d4-a716-446655440000',
    'admin',
    'System Administrator',
    '$2a$12$ZbcSg6botbwvmQV3/wBAfEozQoOn+5V7F8s/5evMUNb7L6FgCmFaEQ=='
FROM dual
WHERE NOT EXISTS (
    SELECT 1 FROM user_credentials
    WHERE user_id = '550e8400-e29b-41d4-a716-446655440000'
);

COMMIT;
